name: "Create Release Mobile Assets"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: fetch repo source
        uses: actions/checkout@v3
        with:
          repository: "Yvictor/scone"
          token: ${{ secrets.SCONE_GITHUB_TOKEN }}
          ref: master
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Bundle zip
        uses: borales/actions-yarn@v4
        with:
          cmd: bundle:encrypt
      - name: Upload production-ready bundle zip
        uses: actions/upload-artifact@v3
        with:
          name: mobile-ota-bundle
          path: |
            *.zip
            key

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: mobile-ota-bundle
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.SINOTRADE_SCONE_GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.zip
            key
