name: "Create Release Mobile Assets"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: mobile-release
    steps:
      - name: fetch repo source
        uses: actions/checkout@v3
        with:
          repository: "Yvictor/scone"
          token: ${{ secrets.SCONE_GITHUB_TOKEN }}
          ref: master
      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
      - name: Create .env file for vite build
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Bundle zip
        uses: borales/actions-yarn@v5
        with:
          cmd: bundle:encrypt
      - name: Upload production-ready bundle zip
        uses: actions/upload-artifact@v3
        with:
          name: mobile-ota-bundle
          path: |
            *.zip
            *.checksum
            key

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
            name: mobile-ota-bundle
      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli
      - name:  Generate changelog
        id: changelog
        run: |
          conventional-changelog -p conventionalcommits -r 2 -o CHANGELOGFULL.md
          tail -n +5 CHANGELOGFULL.md >> ${{ github.workspace }}-CHANGELOG.md
      - name: create github release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.SINOTRADE_SCONE_GITHUB_TOKEN }}
          prerelease: false
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: |
            *.zip
            *.checksum
            key
