name: "Create Release Mobile Assets"

on:
  push:
    tags:
      - "*"

jobs:
  Build:
    name: Build
    runs-on: macos-latest
    environment: mobile-release
    steps:
      - name: fetch repo source for Formal release
        if: "!startsWith(github.ref, 'refs/tags/staging-')"
        uses: actions/checkout@v4
        with:
          repository: "Yvictor/scone"
          token: ${{ secrets.SCONE_GITHUB_TOKEN }}
          ref: master

      - name: fetch repo source for Staging staging
        if: "startsWith(github.ref, 'refs/tags/staging-')"
        uses: actions/checkout@v4
        with:
          repository: "Yvictor/scone"
          token: ${{ secrets.SCONE_GITHUB_TOKEN }}
          ref: staging

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: yarn install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Create .env file for vite build
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build bundle for release
        if: "!startsWith(github.ref, 'refs/tags/staging-')"
        uses: borales/actions-yarn@v5
        with:
          cmd: build
        env:
          VITE_ENV: 'production'

      - name: Build bundle for staging
        if: "startsWith(github.ref, 'refs/tags/staging-')"
        uses: borales/actions-yarn@v5
        with:
          cmd: build
        env:
          VITE_ENV: 'staging'

      - name: Sync Capacitor
        uses: borales/actions-yarn@v5
        with:
          cmd: sync

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Bundle install in ios/App
        run: bundle install
        working-directory: ./ios/App

      - name: Run Fastlane
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'release'
          subdirectory: 'ios/App'
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_P8 }}
          APP_STORE_CONNECT_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.APP_STORE_CONNECT_DISTRIBUTION_CERTIFICATE_BASE64 }}
          APP_STORE_CONNECT_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.APP_STORE_CONNECT_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          APP_STORE_CONNECT_PROVISIONING_PROFILE_BASE64: ${{ secrets.APP_STORE_CONNECT_PROVISIONING_PROFILE_BASE64 }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          XCODE_SIGNING_IDENTITY: ${{ secrets.XCODE_SIGNING_IDENTITY }}

      - name: Bundle zip
        uses: borales/actions-yarn@v5
        with:
          cmd: bundle:encrypt

      - name: Upload production-ready bundle zip
        uses: actions/upload-artifact@v4
        with:
          name: mobile-ota-bundle
          path: |
            *.zip
            *.checksum
            key

  Release:
    name: Release
    needs: Build
    if: "!startsWith(github.ref, 'refs/tags/staging-')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download changelog artifact
        uses: actions/download-artifact@v3
        with:
            name: mobile-ota-bundle

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name:  Generate changelog
        id: changelog
        run: |
          conventional-changelog -p conventionalcommits -r 2 -o CHANGELOGFULL.md
          tail -n +5 CHANGELOGFULL.md >> ${{ github.workspace }}-CHANGELOG.md

      - name: create github release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.SINOTRADE_SCONE_GITHUB_TOKEN }}
          prerelease: false
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: |
            *.zip
            *.checksum
            key
